name: cleverpush_example
description: Demonstrates how to use the cleverpush plugin.

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  package_info: ^0.4.0+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  cleverpush_flutter:
    path: ../

flutter:
  uses-material-design: true
